### PR TITLE
Eric

### PR DESCRIPTION
**Pull request by esodell1**
Added JRE library and persistent storage.

### CODE REVIEW

**Comment by theKrumm** [comment]
I can't make junit tests for some reason.  I keep getting weird errors when
trying to create them.  Did you guys run into this issue?

**Comment by tbs95** [comment]
No, I am not getting any errors from creating Junit tests.

**Comment by theKrumm** [comment]
I really am enjoying all the little stupid things I have to fix on my
computer just to make a java program

**Comment by theKrumm** [comment]
I am sorry I didn't make the meeting today.  I had a family emergency that
I had to take care of.  My phone died, so I asked Tempest to let you guys
know.  Hopefully she told you guys.

-tyler

**Pull request merged**
